### ISSUE TITLE
ChannelType.INVALID not caught after returning from findChannel

### ISSUE THREAD

**Issue by Richardn2002** [Inochi2D/psd-d#4]
Starting from `source/psd/parser.d:145`, the return values from helper function `findChannel()` are used as array indexes. However `findChannel()` may return `ChannelType.INVALID`, which indexes out of bounds. Can have an improvement where this value is caught and meaningful errors are generated. Would be better if `findChannel()` is guaranteed to find a channel with future fixes.

(I do have a PSD file causing the above situation to happen. Already sent to Luna privately.)

**Comment by LunaTheFoxgirl** [comment]
Fixed by https://github.com/Inochi2D/psd-d/commit/9135f90b7f59b1d3413eb77a37c2a0f276f8d345
